require("dotenv").config();
const { Client } = require("pg");

// const items = [
//   {
//     animal_type: "alpaca",
//     item_type: "adult onesie"
//     brand: "jammy mart",
//     price_unit: 32.99,
//     cost_unit: 17.99,
//     base_sku: "alpac001jam-",
//     rating: 4.1,
//     number_reviews: 13,
//     img_front_url: "alpac001f.jpg",
//     img_rear_url: "alpac001r.jpg",
//     img_size_url: "siz_jam001.jpg",
//     tags: ["mammals, camelids"],
//     stock: [
//       { size: "S", units: 1 },
//       { size: "M", units: 0 },
//       { size: "L", units: 2 },
//       { size: "XL", units: 2 },
//     ],
//   },
// ]

// const items = [
//   {
//     animal_type: "alpaca",
//     item_type: "adult onesie",
//     brand: "jammy mart",
//     price_unit: 32.99,
//     cost_unit: 17.99,
//     base_sku: "ALPAC001JAM-",
//     rating: 4.1,
//     number_reviews: 13,
//     images: {
//       front: "alpac001f.jpg",
//       rear: "alpac001r.jpg",
//       size: "siz_jam001.jpg",
//     },
//     tags: ["mammals", "camelids"],
//     stock: [
//       { size: "S", units: 1 },
//       { size: "M", units: 0 },
//       { size: "L", units: 2 },
//       { size: "XL", units: 2 },
//     ],
//   },
// ];

const items = [
  {
    animal_type: "alpaca",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "ALPAC001JAM-",
    rating: 4.1,
    number_reviews: 13,
    images: {
      front: "alpac001f.jpg",
      rear: "alpac001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "camelids"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 0 },
      { size: "L", units: 2 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "axolotl",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "AXOLO001JAM",
    rating: 4.1,
    number_reviews: 9,
    images: {
      front: "axolo001f.jpg",
      rear: "axolo001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["amphibians, salamanders"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 0 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "bear",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "BEARX001JAM",
    rating: 4.2,
    number_reviews: 19,
    images: {
      front: "bearx001f.jpg",
      rear: "bearx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "ursines"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 2 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "bee",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "BEEXX001SPA",
    rating: 3.1,
    number_reviews: 6,
    images: {
      front: "beexx001f.jpg",
      rear: "beexx001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["bugs", "insects"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 2 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "black bear",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "BLABE001JAM",
    rating: 4.5,
    number_reviews: 29,
    images: {
      front: "blabe001f.jpg",
      rear: "blabe001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "ursines"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "black dragon",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "BLADR001DIN",
    rating: 4.5,
    number_reviews: 6,
    images: {
      front: "bladr001f.jpg",
      rear: "bladr001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "mythical", "lizards"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "blue dragon",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "BLUDR001DIN",
    rating: 4.7,
    number_reviews: 5,
    images: {
      front: "bludr001f.jpg",
      rear: "bludr001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "mythical", "lizards"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "bull",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "BULLX001JAM",
    rating: 4.3,
    number_reviews: 24,
    images: {
      front: "bullx001f.jpg",
      rear: "bullx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 3 },
      { size: "L", units: 3 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "butterfly",
    item_type: "adult onesie",
    brand: "mooshi-doo",
    price_unit: 38.99,
    cost_unit: 23.99,
    base_sku: "BUTFL001MOO",
    rating: 3.9,
    number_reviews: 15,
    images: {
      front: "butfl001f.jpg",
      rear: "butfl001r.jpg",
      size: "siz_moo001.jpg",
    },
    tags: ["bugs", "insects"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 2 },
      { size: "L", units: 3 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "caracal",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "CARAC001JAM",
    rating: 3.7,
    number_reviews: 14,
    images: {
      front: "carac001f.jpg",
      rear: "carac001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "felines", "cats"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 2 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "cardinal",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 38.99,
    cost_unit: 23.99,
    base_sku: "CARDI001JAM",
    rating: 4.9,
    number_reviews: 10,
    images: {
      front: "cardi001f.jpg",
      rear: "cardi001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 0 },
      { size: "L", units: 2 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "chameleon",
    item_type: "adult onesie",
    brand: "plushies",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "CHAME001PLU",
    rating: 4.7,
    number_reviews: 5,
    images: {
      front: "chame001f.jpg",
      rear: "chame001r.jpg",
      size: "siz_plu001.jpg",
    },
    tags: ["reptiles", "lizards"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "crow",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "CROWX001JAM",
    rating: 4.1,
    number_reviews: 7,
    images: {
      front: "crowx001f.jpg",
      rear: "crowx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 3 },
      { size: "L", units: 2 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "dalmatian",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "DALMA001SPA",
    rating: 2.1,
    number_reviews: 11,
    images: {
      front: "dalma001f.jpg",
      rear: "dalma001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals", "canines", "doggos"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 2 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "deer",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "DEERX001JAM",
    rating: 4.6,
    number_reviews: 13,
    images: {
      front: "deerx001f.jpg",
      rear: "deerx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 6 },
      { size: "L", units: 3 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "dinosaur",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "DINOS001DIN",
    rating: 4.7,
    number_reviews: 4,
    images: {
      front: "dinos001f.jpg",
      rear: "dinos001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "dinosaurs", "lizards"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 1 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "donkey",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "DONKE001JAM",
    rating: 4.3,
    number_reviews: 7,
    images: {
      front: "donke001f.jpg",
      rear: "donke001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "horseys"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 2 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "eagle",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "EAGLE001JAM",
    rating: 4.2,
    number_reviews: 5,
    images: {
      front: "eagle001f.jpg",
      rear: "eagle001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 2 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "flamingo",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "FLAMI001JAM",
    rating: 4.1,
    number_reviews: 5,
    images: {
      front: "flami001f.jpg",
      rear: "flami001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "flying squirrel",
    item_type: "adult onesie",
    brand: "plushies",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "FLYSQ001PLU",
    rating: 3.0,
    number_reviews: 2,
    images: {
      front: "flysq001f.jpg",
      rear: "flysq001r.jpg",
      size: "siz_plu001.jpg",
    },
    tags: ["mammals", "rodents"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 2 },
      { size: "L", units: 3 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "fox",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "FOXXX001JAM",
    rating: 4.2,
    number_reviews: 16,
    images: {
      front: "foxxx001f.jpg",
      rear: "foxxx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "canines", "doggos"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 2 },
      { size: "L", units: 1 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "frog",
    item_type: "adult onesie",
    brand: "plushies",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "FROGX001PLU",
    rating: 3.8,
    number_reviews: 12,
    images: {
      front: "frogx001f.jpg",
      rear: "frogx001r.jpg",
      size: "siz_plu001.jpg",
    },
    tags: ["amphibians"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 2 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "giraffe",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "GIRAF001JAM",
    rating: 4.1,
    number_reviews: 7,
    images: {
      front: "giraf001f.jpg",
      rear: "giraf001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "housefly",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "HOUFL001SPA",
    rating: 2.4,
    number_reviews: 6,
    images: {
      front: "houfl001f.jpg",
      rear: "houfl001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["bugs", "insects"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "kangaroo",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "KANGA001JAM",
    rating: 4.6,
    number_reviews: 22,
    images: {
      front: "kanga001f.jpg",
      rear: "kanga001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "marsupials"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 3 },
      { size: "L", units: 1 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "koala",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "KOALA001JAM",
    rating: 3.9,
    number_reviews: 15,
    images: {
      front: "koala001f.jpg",
      rear: "koala001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "marsupials"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 1 },
      { size: "L", units: 3 },
      { size: "XL", units: 3 },
    ],
  },
  {
    animal_type: "leopard",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "LEOPA001SPA",
    rating: 3.5,
    number_reviews: 14,
    images: {
      front: "leopa001f.jpg",
      rear: "leopa001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals", "felines", "cats"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 1 },
      { size: "L", units: 4 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "lion",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "LIONX001JAM",
    rating: 3.9,
    number_reviews: 18,
    images: {
      front: "lionx001f.jpg",
      rear: "lionx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "felines", "cats"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 2 },
      { size: "L", units: 3 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "macaw",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "MACAW001JAM",
    rating: 4.1,
    number_reviews: 6,
    images: {
      front: "macaw001f.jpg",
      rear: "macaw001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "mallard",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "MALLA001JAM",
    rating: 4.0,
    number_reviews: 4,
    images: {
      front: "mallax001f.jpg",
      rear: "malla001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 1 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "monkey",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "MONKE001JAM",
    rating: 4.0,
    number_reviews: 11,
    images: {
      front: "monke001f.jpg",
      rear: "monke001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 3 },
      { size: "L", units: 2 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "moose",
    item_type: "adult onesie",
    brand: "plushies",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "MOOSE001PLU",
    rating: 4.7,
    number_reviews: 4,
    images: {
      front: "moose001f.jpg",
      rear: "moose001r.jpg",
      size: "siz_plu001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 2 },
      { size: "L", units: 1 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "moth",
    item_type: "adult onesie",
    brand: "mooshi-doo",
    price_unit: 38.99,
    cost_unit: 23.99,
    base_sku: "MOTHX001MOO",
    rating: 3.4,
    number_reviews: 1,
    images: {
      front: "mothx001f.jpg",
      rear: "mothx001r.jpg",
      size: "siz_moo001.jpg",
    },
    tags: ["bugs", "insects"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "mouse",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "MOUSE001SPA",
    rating: 3.1,
    number_reviews: 16,
    images: {
      front: "mouse001f.jpg",
      rear: "mouse001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals", "rodents"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 1 },
      { size: "L", units: 3 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "panda",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "PANDA001JAM",
    rating: 3.9,
    number_reviews: 7,
    images: {
      front: "panda001f.jpg",
      rear: "panda001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "ursines"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 2 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "penguin",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "PENGU001SPA",
    rating: 4.3,
    number_reviews: 11,
    images: {
      front: "pengu001f.jpg",
      rear: "pengu001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 0 },
      { size: "L", units: 1 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "pig",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "PIGXX001SPA",
    rating: 4.6,
    number_reviews: 17,
    images: {
      front: "pigxx001f.jpg",
      rear: "pigxx001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 3 },
      { size: "L", units: 3 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "pigeon",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "PIGEO001JAM",
    rating: 4.2,
    number_reviews: 4,
    images: {
      front: "pigeo001f.jpg",
      rear: "pigeo001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 3 },
    ],
  },
  {
    animal_type: "rabbit",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "RABBI001JAM",
    rating: 4.3,
    number_reviews: 7,
    images: {
      front: "rabbi001f.jpg",
      rear: "rabbi001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 5 },
      { size: "L", units: 2 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "raccoon",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "RACCO001JAM",
    rating: 4.1,
    number_reviews: 9,
    images: {
      front: "racco001f.jpg",
      rear: "racco001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 3 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "rat",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "RATXX001JAM",
    rating: 3.9,
    number_reviews: 5,
    images: {
      front: "ratxx001f.jpg",
      rear: "ratxx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "rodents"],
    stock: [
      { size: "S", units: 3 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "red panda",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "REDPA001JAM",
    rating: 3.5,
    number_reviews: 12,
    images: {
      front: "redpa001f.jpg",
      rear: "redpa001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 4 },
    ],
  },
  {
    animal_type: "rhino",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "RHINO001JAM",
    rating: 4.0,
    number_reviews: 7,
    images: {
      front: "rhino001f.jpg",
      rear: "rhino001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 2 },
      { size: "L", units: 0 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "rooster",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 36.99,
    cost_unit: 20.91,
    base_sku: "ROOST001JAM",
    rating: 3.9,
    number_reviews: 6,
    images: {
      front: "roost001f.jpg",
      rear: "roost001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 1 },
      { size: "L", units: 1 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "sand cat",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "SANCA001JAM",
    rating: 2.7,
    number_reviews: 3,
    images: {
      front: "sandca001f.jpg",
      rear: "sandca001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "felines", "cats"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "seagull",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 38.99,
    cost_unit: 23.99,
    base_sku: "SEAGU001JAM",
    rating: 4.3,
    number_reviews: 9,
    images: {
      front: "seagu001f.jpg",
      rear: "seagu001r.jpg",
      size: "siz_jam001.jpg",
      tags: ["birds"],
    },

    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 3 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "sea otter",
    item_type: "adult onesie",
    brand: "plushies",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "SEAOT001PLU",
    rating: 5.0,
    number_reviews: 11,
    images: {
      front: "seaot001f.jpg",
      rear: "seaot001r.jpg",
      size: "siz_plu001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 2 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "sloth",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "SLOTH001JAM",
    rating: 4.2,
    number_reviews: 8,
    images: {
      front: "sloth001f.jpg",
      rear: "sloth001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 3 },
      { size: "L", units: 0 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "spider",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "SPIDE001JAM",
    rating: 3.9,
    number_reviews: 2,
    images: {
      front: "spide001f.jpg",
      rear: "spide001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["bugs", "arachnids"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 0 },
      { size: "L", units: 0 },
      { size: "XL", units: 4 },
    ],
  },
  {
    animal_type: "squirrel",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "SQUIR001JAM",
    rating: 4.1,
    number_reviews: 12,
    images: {
      front: "squir001f.jpg",
      rear: "squir001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "rodents"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 0 },
      { size: "L", units: 1 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "stegosaurus",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "STEGO001DIN",
    rating: 4.5,
    number_reviews: 7,
    images: {
      front: "stego001f.jpg",
      rear: "stego001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "dinosaurs", "lizards"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 1 },
      { size: "L", units: 1 },
      { size: "XL", units: 1 },
    ],
  },
  {
    animal_type: "tiger",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "TIGER001SPA",
    rating: 3.3,
    number_reviews: 15,
    images: {
      front: "tiger001f.jpg",
      rear: "tiger001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals", "felines", "cats"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 3 },
      { size: "L", units: 0 },
      { size: "XL", units: 3 },
    ],
  },
  {
    animal_type: "triceratops",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 42.99,
    cost_unit: 23.45,
    base_sku: "TRICE001DIN",
    rating: 4.3,
    number_reviews: 5,
    images: {
      front: "trice001f.jpg",
      rear: "trice001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "dinosaurs", "lizards"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 1 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
  {
    animal_type: "turkey",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 38.99,
    cost_unit: 23.99,
    base_sku: "TURKE001JAM",
    rating: 3.8,
    number_reviews: 19,
    images: {
      front: "turke001f.jpg",
      rear: "turke001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["birds"],
    stock: [
      { size: "S", units: 4 },
      { size: "M", units: 3 },
      { size: "L", units: 2 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "T-Rex",
    item_type: "adult onesie",
    brand: "dinojama",
    price_unit: 39.99,
    cost_unit: 23.33,
    base_sku: "TREXX001DIN",
    rating: 4.9,
    number_reviews: 6,
    images: {
      front: "trexx001f.jpg",
      rear: "trexx001r.jpg",
      size: "siz_din001.jpg",
    },
    tags: ["reptiles", "dinosaurs", "lizards"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "unicorn",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "UNICO001JAM",
    rating: 4.2,
    number_reviews: 23,
    images: {
      front: "unico001f.jpg",
      rear: "unico001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "horseys", "mythical"],
    stock: [
      { size: "S", units: 5 },
      { size: "M", units: 2 },
      { size: "L", units: 4 },
      { size: "XL", units: 4 },
    ],
  },
  {
    animal_type: "wendigo",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "WENDI001SPA",
    rating: 2.3,
    number_reviews: 4,
    images: {
      front: "wendi001f.jpg",
      rear: "wendi001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mythical"],
    stock: [
      { size: "S", units: 0 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 2 },
    ],
  },
  {
    animal_type: "wolf",
    item_type: "adult onesie",
    brand: "jammy mart",
    price_unit: 34.99,
    cost_unit: 19.09,
    base_sku: "WOLFX001JAM",
    rating: 4.3,
    number_reviews: 9,
    images: {
      front: "wolfx001f.jpg",
      rear: "wolfx001r.jpg",
      size: "siz_jam001.jpg",
    },
    tags: ["mammals", "canines", "doggos"],
    stock: [
      { size: "S", units: 2 },
      { size: "M", units: 1 },
      { size: "L", units: 0 },
      { size: "XL", units: 3 },
    ],
  },
  {
    animal_type: "zebra",
    item_type: "adult onesie",
    brand: "spanko",
    price_unit: 32.99,
    cost_unit: 17.99,
    base_sku: "ZEBRA001SPA",
    rating: 3.4,
    number_reviews: 8,
    images: {
      front: "zebra001f.jpg",
      rear: "zebra001r.jpg",
      size: "siz_spa001.jpg",
    },
    tags: ["mammals", "horseys"],
    stock: [
      { size: "S", units: 1 },
      { size: "M", units: 1 },
      { size: "L", units: 1 },
      { size: "XL", units: 0 },
    ],
  },
];


async function main() {
  console.log("Seeding products...");

  const client = new Client({
    user: process.env.PG_USER,
    password: process.env.PG_PASSWORD,
    host: process.env.PG_HOST,
    port: Number(process.env.PG_PORT),
    database: process.env.PG_DATABASE,
  });

  await client.connect();

  for (const item of items) {
    /* 1️⃣ Insert product */
    const productRes = await client.query(
      `
      INSERT INTO products (
        animal_type,
        item_type,
        brand,
        price_unit,
        cost_unit,
        base_sku,
        rating,
        review_count
      )
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
      RETURNING id;
      `,
      [
        item.animal_type,
        item.item_type,
        item.brand,
        item.price_unit,
        item.cost_unit,
        item.base_sku,
        item.rating,
        item.number_reviews,
      ]
    );

    const productId = productRes.rows[0].id;

    /* 2️⃣ Insert images */
    for (const [type, filename] of Object.entries(item.images)) {
      await client.query(
        `
        INSERT INTO product_images (product_id, type, filename)
        VALUES ($1, $2, $3);
        `,
        [productId, type, filename]
      );
    }

    /* 3️⃣ Insert tags */
    for (const tag of item.tags) {
      const tagRes = await client.query(
        `
        INSERT INTO tags (name)
        VALUES ($1)
        ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
        RETURNING id;
        `,
        [tag]
      );

      const tagId = tagRes.rows[0].id;

      await client.query(
        `
        INSERT INTO product_tags (product_id, tag_id)
        VALUES ($1, $2)
        ON CONFLICT DO NOTHING;
        `,
        [productId, tagId]
      );
    }

    /* 4️⃣ Insert inventory + SKUs */
    for (const { size, units } of item.stock) {
      const sizeRes = await client.query(
        `
        INSERT INTO sizes (code)
        VALUES ($1)
        ON CONFLICT (code) DO UPDATE SET code = EXCLUDED.code
        RETURNING id;
        `,
        [size]
      );

      const sizeId = sizeRes.rows[0].id;
      const sku = `${item.base_sku}${size}`;

      await client.query(
        `
        INSERT INTO inventory (product_id, size_id, sku, units)
        VALUES ($1, $2, $3, $4);
        `,
        [productId, sizeId, sku, units]
      );
    }
  }

  await client.end();
  console.log("Product seeding complete!");
}

main().catch((err) => {
  console.error("Error seeding DB:", err);
});

